// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CaioSamuelTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void caioSamuel() {
    driver.get("https://www.icmc.usp.br/");
    driver.manage().window().setSize(new Dimension(854, 480));
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".item-129 > a")).click();
    driver.findElement(By.linkText("Docentes")).click();
    js.executeScript("window.scrollTo(0,31)");
    driver.findElement(By.name("nome_busca")).click();
    driver.findElement(By.name("nome_busca")).sendKeys("silva");
    driver.findElement(By.name("nome_busca")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".col-xs-6:nth-child(1) .img-responsive")).click();
  }
}
